version: '3.8'
services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "9700:5000"
    volumes:
      - "/home/migo/.local"
      - "./:/home/migo"
  mongo:
    image: "mongo"
    ports: 
      - "27017:27017"
    volumes:
      - "/var/lib/docker/volumes/mong_db/_data:/data/db"